name: 'build app'

on:
  workflow_dispatch:
#   push:
#     branches: main

jobs:
  publish-tauri:
    permissions:
      contents: write
    environment: tauri
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'blacksmith-6vcpu-macos-15' # for Arm based macs (M1 and above).
            args: '--target aarch64-apple-darwin'
            type: 'mac'
          - platform: 'blacksmith-6vcpu-macos-15' # for Intel based macs.
            args: '--target x86_64-apple-darwin'
            type: 'mac'
          - platform: 'blacksmith-2vcpu-ubuntu-2404-arm'
            args: ''
            type: 'ubuntu'
          - platform: 'blacksmith-2vcpu-windows-2025'
            args: ''
            type: 'windows'

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v6

      - name: install dependencies (ubuntu only)
        if: matrix.type == 'ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf xdg-open

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable # Set this to dtolnay/rust-toolchain@nightly
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.type == 'mac' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: install frontend dependencies
        run: bun install

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_PRIVATE_PASSWORD }}
        with:
          tagName: __VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}